# Generated by Django 6.0.5 on 2026-05-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('genero', models.CharField(choices=[('comedia', 'Comédia'), ('aventura', 'Aventura'), ('misterio', 'Mistério'), ('acao', 'Ação'), ('romance', 'Romance')], max_length=20)),
                ('estudio', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
            ],
        ),
    ]
