# Generated by Django 6.0.5 on 2026-05-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desenhos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desenho',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas/'),
        ),
        migrations.AddField(
            model_name='desenho',
            name='emissora',
            field=models.CharField(default='desconhecida', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desenho',
            name='genero',
            field=models.CharField(choices=[('comedia', 'Comédia'), ('aventura', 'Aventura'), ('misterio', 'Mistério'), ('acao', 'Ação'), ('romance', 'Romance')], max_length=100),
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('desenhos', models.ManyToManyField(to='desenhos.desenho')),
            ],
        ),
    ]
