# Generated by Django 5.2.1 on 2026-05-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desenhos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desenho',
            name='emissora',
            field=models.CharField(default='Desconhecida', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desenho',
            name='genero',
            field=models.CharField(choices=[('comedia', 'Comédia'), ('aventura', 'Aventura'), ('misterio', 'Mistério'), ('acao', 'Ação'), ('romance', 'Romance'), ('fantasia', 'Fantasia'), ('ficcao_cientifica', 'Ficção científica')], max_length=20),
        ),
        migrations.AlterField(
            model_name='desenho',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
