# Generated by Django 6.0.5 on 2026-05-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desenhos', '0002_desenho_capa_desenho_emissora_alter_desenho_genero_and_more'),
        ('desenhos', '0002_desenho_emissora_alter_desenho_genero_and_more'),
    ]

    operations = [
    ]
