# Generated by Django 5.2.1 on 2026-06-05 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desenhos', '0003_merge_20260529_1430'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='desenho',
            name='genero',
            field=models.CharField(choices=[('comedia', 'Comédia'), ('aventura', 'Aventura'), ('misterio', 'Mistério'), ('acao', 'Ação'), ('romance', 'Romance'), ('fantasia', 'Fantasia'), ('ficcao_cientifica', 'Ficção científica')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lista',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfis/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('email_confirmado', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
